.\" Man page for mate-geyes-applet.
.TH "MATE-GEYES-APPLET" "1" "10 februar 2002" "" ""
.SH NAME
mate-geyes-applet \- gEyes Applet for the MATE panel.
.SH SYNOPSIS

\fBmate-geyes-applet\fR [ \fB--activate-goad-server \fI[=GOAD_ID]\fB\fR ]

.SH "DESCRIPTION"
.PP
\fBmate-geyes-applet\fR is a pair of eyes which follow your
mouse pointer around the screen.
.PP
To add this applet to a Panel, right-click on the Panel and
choose Applets->Amusements->gEyes.
.SH "OPTIONS"
.TP
\fB--activate-goad-server\fR
(Internal use only) GOAD server ID to activate.

GOAD_ID is usually the applet name [\fBgeyes_applet\fR]
.SH "AUTHOR"
.PP
This manual page was written by Christian Marillat <marillat@debian.org> for
the Debian GNU/Linux system (but may be used by others).
