#!/bin/bash

# fill it
pkgname=mate-applets
pkgver=2011.08.31
pkgrel=1
pkgdesc="MATE Applets"
depends=('gstreamer0.10-plugins-base' 'mate-panel' 'mate-character-map' 'libgtop2-7' 'libmatenotify' 'cpufrequtils')
conflicts=('gnome-applets-data')

# editar esta funcion!
build() {
	cd $pkgsrc
	# descomprimir
	tar xvzf download
	# entramos a la carpeta
	cd ${pkgname}

	mate-doc-prepare
	autoreconf -i
	automake

	./configure --prefix=/usr --sysconfdir=/etc \
		--libexecdir=/usr/lib/${pkgname} \
		--localstatedir=/var --disable-static \
		--disable-scrollkeeper --enable-mixer-applet \
		--disable-schemas-install || return 1

	# there is some pre-compiled files on the tar
	make clean
	make || return 1

	make MATECONF_DISABLE_MAKEFILE_SCHEMA_INSTALL=1 DESTDIR="${pkgdir}" install || return 1
	#rm -f ${pkgdir}/usr/lib/*.la # can be used options=(!libtools)

	install -m755 -d "${pkgdir}/usr/share/mateconf/schemas"
	mateconf-merge-schema "${pkgdir}/usr/share/mateconf/schemas/${pkgname}.schemas" --domain ${pkgname} ${pkgdir}/etc/mateconf/schemas/*.schemas || return 1
	rm -f ${pkgdir}/etc/mateconf/schemas/*.schemas
}

# esto incluye la parte que se repite en la mayoria de los builds
. /usr/share/mate-doc-utils/mate-debian.sh
