#!/usr/bin/env python

import sys, mate_invest.chart

import gi
gi.require_version("Gtk", mate_invest.defs.GTK_API_VERSION)
from gi.repository import Gtk

# Prepare i18n
import gettext, locale
gettext.bindtextdomain(mate_invest.defs.GETTEXT_PACKAGE, mate_invest.defs.MATELOCALEDIR)
gettext.textdomain(mate_invest.defs.GETTEXT_PACKAGE)
locale.bindtextdomain(mate_invest.defs.GETTEXT_PACKAGE, mate_invest.defs.MATELOCALEDIR)
locale.textdomain(mate_invest.defs.GETTEXT_PACKAGE)

if __name__ == "__main__":
	win = mate_invest.chart.show_chart(sys.argv[1:])
	win.connect("destroy", lambda x: Gtk.main_quit())
	Gtk.main()
